README.md, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts
=> [ENG-923] Transfer NFT

README.md, src/@types/graphql.ts, src/Refinable.ts, src/chains.ts, src/examples/cancelAuction.ts, src/examples/endAuction.ts, src/examples/item/itemsOnSale.ts, src/graphql/fragments.ts, src/graphql/items.ts, src/nft/AbstractNFT.ts, src/web3.ts
This will Allow the user to get his items currently on sale
=> [ENG-865]  Get items on sale

README.md, src/Refinable.ts, src/examples/item/itemsOnAuction.ts
- Get items on auction of a user
- This still returns items whose auctions are ended
=> [ENG-866] get items on auction

README.md, src/@types/graphql.ts, src/Refinable.ts, src/examples/item/getItems.ts, src/examples/listForSale.ts, src/graphql/fragments.ts, src/graphql/items.ts
Description:
1. This will allow SDK users to get data for a user
=> [ENG-863] Get items

src/nft/builder/NFTBuilder.ts
Description:
App was having issue with creating NFTs,  because thumbnail was not included in SDK.
=> update create method

package.json, src/@types/graphql.ts, src/RefinableContracts.ts, src/config/sdk.ts, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts
Description:
- Update getBaseContracts method
- Add cancel to AbstractNFT
=> Fix wrong contract fetch

package.json, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts
Description:
Enabling transferProxy in diamond contracts, so we don't need to check for  transferProxy removing check logic
=> deploy diamond contracts

package.json, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/offer/SaleOffer.ts
Fixed the use of incorrect supply during cancelling a erc1155 sale. Wanted to write a test, but saw it was actually already covered. So its good to remember to run em
=> fix(ENG-1559): resolve issue with close sale 1155

package.json, src/@types/graphql.ts, src/config/sdk.ts, src/nft/AbstractNFT.ts, src/nft/ERC721NFT.ts, tests/unit-tests/erc1155.test.ts, tests/unit-tests/erc721.test.ts
- Contract v4 for Polygon and BSC
=> [DEV-1553] [DEV-1501] [DEV-1566] Deploy auction contracts for diamond

package.json, src/@types/graphql.ts, src/graphql/items.ts, src/nft/AbstractNFT.ts
Add refresh metadata to SDK and use it from here
=> [DEV-1215] Support refreshing metadata on NFTs

package.json
Description 
v1.3.0 -->> 1.3.1
=> Update SDK version

src/@types/graphql.ts, src/RefinableContracts.ts, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts
Description:
update getRefinablecontracts method to support types
=> [DEV-1553] Blockchain Implementation 

package.json
Change sdk version from 1.3.1 => 1.3.2
=> bump sdk version

package.json, src/@types/graphql.ts, src/config/sdk.ts, src/nft/ERC1155NFT.ts
- Support VIP, Private, Public sales
- Added option to use SDK without a signer (for when you don't want to do stuff that requires signing, useful for custom sites)
=> Support launchpads

package.json, src/config/sdk.ts, src/nft/AbstractNFT.ts, src/nft/builder/IBuilder.ts, src/nft/builder/NFTBatchBuilder.ts, src/nft/builder/NFTBuilder.ts, tests/unit-tests/erc1155.test.ts, tests/unit-tests/erc721.test.ts
- Fix issue with batch putting for sale
=> feat: Release candidate 3

package.json, src/@types/graphql.ts, src/offer/SaleOffer.ts
Allow passing metadata to purchase
=> Allow passing metadata to purchase

package.json, src/refinable/account/EvmAccount.ts, tests/unit/Account.spec.ts
Very strange, both should give the same result, but they do not. Not sure why this is the first time we had issues with this.
=> fix(DEV-1767): incorrect zero balance

src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts
a whitelist only makes sense if the start date of the NFT sale is later than the whitelist start date.
This PR adds validation on the dates
=> Validate launchpad dates

examples/evm/sale/whitelistedSale.ts, examples/item/checkout.ts, src/@types/graphql.ts, src/config/sdk.ts, src/graphql/fragments.ts, src/nft/AbstractEvmNFT.ts, src/nft/interfaces/Voucher.ts
- Allow whitelisted price sales
=> Add whitelisted price sale

examples/evm/sale/whitelistedSale.ts, examples/item/checkout.ts, package.json, src/@types/graphql.ts, src/config/sdk.ts, src/graphql/fragments.ts, src/nft/AbstractEvmNFT.ts, src/nft/interfaces/Voucher.ts
- Allow whitelisted price sales
=> Allow whitelisted price sale

examples/evm/sale/lazyMintSale.ts, package.json, src/@types/graphql.ts, src/graphql/sale.ts, src/nft/AbstractEvmNFT.ts, src/nft/AbstractNFT.ts, src/offer/MintOffer.ts, src/offer/Offer.ts, src/offer/OfferFactory.ts, src/refinable/Chain.ts, src/refinable/RefinableBaseClient.ts, src/refinable/offer/OfferClient.ts
- Allow creating mint offers 
- Created offers namespace
- Refactored chain
=> [ENG-1911] Create MintOffers

package.json, src/config/chains.ts, src/interfaces/Network.ts
Added the Goerli chain to the chain config
=> feat(DEV-2141): introduce goerli

package.json, src/@types/graphql.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts, src/nft/SPLNFT.ts, src/nft/builder/NFTBuilder.ts
Include chainId for createOffer and finishMint
=> fix: collections for finishMint and createOffer

package.json, src/@types/graphql.ts, src/enums/royalty-type.enum.ts, src/index.ts, src/refinable/Contracts.ts, src/refinable/RoyaltyRegistry.ts, src/refinable/client/RefinableEvmClient.ts, yarn.lock
Adds RoyaltyRegistry to be able to fetch, set and clear token royalties
=> feat(DEV-1825): self-serving royalties

package.json, src/nft/AbstractEvmNFT.ts
=> Missing chainId in CREATE_OFFER

package.json, src/config/chains.ts, src/nft/ERC721NFT.ts
the current polygon RPC doesn't always work properly. Switch it by a more reliable one.
Added gas estimation fall back in case the normal one fails.
=> chore: switch malfunctioning RPC

src/@types/graphql.ts, src/Contract.ts, src/graphql/collections.ts, src/graphql/contracts.ts, src/refinable/Contracts.ts, src/refinable/interfaces/Contracts.ts
Make it easier to selfserve collections.
- Split up mutations in 2 parts for SoC
- Add `banner` field to allow setting a banner
=> [DEV-2096] Selfserve collection

package.json, src/refinable/RoyaltyRegistry.ts
Makes sure to return the actual tx so that we can wait for its execution.
=> improvement: return mutating tx

package.json, src/@types/graphql.ts, src/config/sdk.ts, src/errors/SimulationFailedError.ts, src/errors/index.ts, src/graphql/fragments.ts, src/graphql/utils.ts, src/index.ts, src/nft/AbstractEvmNFT.ts, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts, src/nft/SPLNFT.ts, src/nft/builder/NFTBuilder.ts, src/offer/AuctionOffer.ts, src/offer/MintOffer.ts, src/offer/Offer.ts, src/offer/SaleOffer.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/index.ts, src/refinable/ContractFactory.ts, src/refinable/Contracts.ts, src/refinable/Refinable.ts, src/refinable/checkout/CheckoutClient.ts, src/refinable/offer/OfferClient.ts, src/transaction/simulate.ts, tests/helpers/client.ts, tests/unit/NFTBuilder.spec.ts, yarn.lock
Adds support to buy NFTs from external platforms directly through Refinable
=> Support Buying Looksrare items through Refinable

package.json, src/offer/SaleOffer.ts, src/transaction/simulate.ts
=> [DEV-2315] broken provider

package.json, src/refinable/account/EvmAccount.ts
Fixes "Sending a transaction requires a signer" during purchase using erc20 tokens
=> fix: token approval signer error

package.json, src/offer/SaleOffer.ts
- WETH Purchases on looksrare were not calculated correctly. value has to be 0, currency is set in the contract
=> fix: WETH purchase

package.json, src/@types/graphql.ts, src/refinable/ContractFactory.ts
Reverts refinableco/refinable-sdk#105
=> Revert "post maxSupply on graphql mutation"

package.json, src/@types/graphql.ts, src/graphql/x2y2.ts, src/offer/SaleOffer.ts, src/platform/X2Y2Platform.ts, src/platform/index.ts
because requesting from browser using sdk is not allowed by x2y2, we will have to request via backend
=> [lab-13] support x2y2

package.json, src/@types/graphql.ts, src/graphql/sale.ts, src/offer/MintOffer.ts, src/refinable/client/RefinableEvmClient.ts
Add method to update some properties on the mintoffer
=> feat: allow updating mint offer

package.json, src/offer/MintOffer.ts
By lack of a DB, I wasn't able to test my previous fix locally. Hence why a bug appeared. Was using the getContract which uses offer.contractAddress. But offer does not exist yet while putting for offer.
=> fix: contractaddress of null

package.json, src/@types/graphql.ts, src/config/chains.ts
=> feat(DEV-2432): support APE payment

examples/evm/sale/lazyMintSale.ts, examples/evm/sale/lazyWhitelistedMintSale.ts, package.json, src/@types/graphql.ts, src/offer/MintOffer.ts, tests/e2e/mintOffer.e2e.spec.ts
`previewImage` was a bit confusing as it also supports video similar to the mint method.
=> refactor: rename previewImage to previewFile

package.json, src/config/chains.ts
Fix wrong decimals for usdt and usdc
=> fix: Wrong decimals for USDT and USDC

src/index.ts, src/nft/AbstractEvmNFT.ts, src/nft/ERC721NFT.ts, src/nft/interfaces/SaleStatusStep.ts, src/offer/SaleOffer.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/X2Y2Platform.ts, src/platform/index.ts
List for sale for looksrare is becoming rather big as there were a lot of steps that were not taken in account.
Start with the following:
- Prepare list for sale for external platforms
- Rework list for sale to support showing steps
=> [DEV-2486] list for sale steps

package.json, src/@types/graphql.ts, src/index.ts, src/interfaces/Signer.ts, src/nft/AbstractEvmNFT.ts, src/nft/ERC721NFT.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/X2Y2Platform.ts, src/refinable/signer/EvmSigner.ts
- Add listing on looksrare (Boilerplate)
=> [DEV-2486] looksrare list for sale (Part 2)

package.json, src/offer/Offer.ts, src/offer/SaleOffer.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/X2Y2Platform.ts, src/refinable/contract/ContractWrapper.ts
Fixes external purchases with erc20 tokens
=> fix: approve erc20 external purchase

package.json, src/nft/ERC721NFT.ts, src/nft/interfaces/SaleStatusStep.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/X2Y2Platform.ts
Approve the looksrare transfer proxy when listing for sale
=> [DEV-2486] Looksrare listing: Approval

package.json, src/platform/LooksrarePlatform.ts
tested buy and list on sale on looksrare against sale contract SaleV4_1_2
=> [dev-2543] invalid params

package.json, src/errors/SimulationFailedError.ts, src/offer/SaleOffer.ts, src/transaction/simulate.ts
This will accompany my backend changes to make the frontend agnostic for any edge cases that tenderly might have. Remove fee calculation to prevent errors happening before running the simulation
=> improvement: less error prone simulation

package.json, src/refinable/Contracts.ts, src/refinable/client/RefinableEvmClient.ts, src/refinable/contract/AbstractWhitelistContract.ts, src/refinable/contract/Erc1155WhitelistContract.ts, src/refinable/contract/Erc721WhitelistContract.ts
Had to add a batch of whitelist addresses to a contract for marketing. Implemented it into the SDK for future easy of use.
=> improvement: whitelist methods

package.json, src/platform/X2Y2Platform.ts
tested on local to list on sale for both Looksrare and X2Y2
=> fix: correct provider usage

src/@types/graphql.ts, src/nft/AbstractEvmNFT.ts, src/nft/AbstractNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts, src/nft/interfaces/CancelSaleStatusStep.ts, src/platform/AbstractPlatform.ts, src/platform/LooksrarePlatform.ts, src/platform/OpenseaPlatform.ts, src/platform/X2Y2Platform.ts, src/refinable/contract/ContractWrapper.ts
Extend platforms to allow for sale cancelation. Decided to expose it on the `nft` rather than `offer`.
=> [DEV-2591] Mass Cancel

package.json, src/errors/InsufficientBalanceError.ts, src/nft/AbstractEvmNFT.ts, src/nft/ERC1155NFT.ts, src/nft/ERC721NFT.ts, src/nft/builder/NFTBuilder.ts, src/utils/parse-error.ts, yarn.lock
- Check balance before listing for sale to avoid invalid state to give the opportunity to list for sale
- refactor listForSale to remove code duplication
=> improvement(DEV-2628): put for sale balance check
